const data = [
  {
    "id": "1",
    "title": "CRESTA BLACK - HYBRID RESIN",
    "pic": "./image/ceil1.jpg",
    "Price": "$729.00",
    "newPrice": "600.00",
    "color": "Black",
    "Category": "Ceiling Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(123 reviews)"
  },
  {
    "id": "2",
    "title": "GLIDER 3.0 BLACK ALUMINIUM",
    "pic": "./image/ceil2.jpg",
    "Price": "$1270.00",
    "newPrice": "1111.00",
    "color": "Black",
    "Category": "Ceiling Fans",
    "Height": "500-800 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "3.6/20 W",
    "temp": "32 to 100°F",
    "current": "0.04/0.28 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(120 reviews)"
  },
  {
    "id": "3",
    "title": "BERPHY OIL-RUBBED BRONZE",
    "pic": "./image/ceil3.jpg",
    "Price": "$729.00",
    "newPrice": "600.00",
    "color": "Black",
    "Category": "Ceiling Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(100 reviews)"
  },
  {
    "id": "4",
    "title": "CRESTA BLACK - HYBRID RESIN",
    "pic": "./image/ceil4.jpg",
    "Price": "$729.00",
    "newPrice": "600.00",
    "color": "White",
    "Category": "Ceiling Fans",
    "Height": "500-800 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "33 to 108°F",
    "current": "0.04/0.3 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(99 reviews)"
  },
  {
    "id": "5",
    "title": "GLIDER 3.0 BRUSHED COPPER",
    "pic": "./image/ceil5.jpg",
    "Price": "$1270.00",
    "newPrice": "1111.00",
    "color": "Brown",
    "Category": "Ceiling Fans",
    "Height": "500-800 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "origin": "USA",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "review": "(130 reviews)"
  },
  {
    "id": "6",
    "title": "ZENOTTA BLACK ALUMINIUM",
    "pic": "./image/ceil6.jpg",
    "Price": "$1015.00",
    "newPrice": "900.00",
    "color": "Black",
    "Category": "Ceiling Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(135 reviews)"
  },
  {
    "id": "7",
    "title": "ZENOTTA WHITE ALUMINIUM",
    "pic": "./image/ceil7.jpg",
    "Price": "$1015.00",
    "newPrice": "900.00",
    "color": "White",
    "Category": "Ceiling Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "origin": "USA",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "review": "(90 reviews)"
  },
  {
    "id": "8",
    "title": "GLIDER 3.0 COCOA",
    "pic": "./image/ceil8.jpg",
    "Price": "$1015.00",
    "newPrice": "900.00",
    "color": "Brown",
    "Category": "Ceiling Fans",
    "Height": "500-800 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "35 to 105°F",
    "current": "0.04/0.3 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(98 reviews)"
  },
  {
    "id": "9",
    "title": "VERPHY BRUSHED ALUMINIUM",
    "pic": "./image/ceil9.jpg",
    "Price": "$729.00",
    "newPrice": "600.00",
    "color": "White",
    "Category": "Ceiling Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.04/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(200 reviews)"
  },
  {
    "id": "10",
    "title": "VERPHY WHITE ALUMINIUM",
    "pic": "./image/ceil10.jpg",
    "Price": "$729.00",
    "newPrice": "600.00",
    "color": "White",
    "Category": "Ceiling Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.038/0.29 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "Ceiling fans reduce perceived temperature. Ceiling fans not only circulate air and balance the heat in the room, but also spread a gentle breeze from the ceiling, effectively reducing perceived temperature levels. The perceived temperature can vary by approximately 3 degrees Celsius when there is a breeze compared to when there is no breeze. Let the device help you create a comfortable space - Motion sensor The motion sensor detects human movement and activity within its detection range. The sensor will then respond to activity intensity by changing the fan speed.",
    "origin": "USA",
    "review": "(230 reviews)"
  },
  {
    "id": "11",
    "title": "COLOSSUS SERIES BLUE",
    "pic": "./image/stand1.png",
    "Price": "$58.31",
    "newPrice": "50.00",
    "color": "Blue",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "origin": "China",
    "review": "(230 reviews)"
  },
  {
    "id": "12",
    "title": "STARWIND SERIES BLACK AND YELLOW",
    "pic": "./image/stand2.png",
    "Price": "$46.94",
    "newPrice": "40.00",
    "color": "Brown",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "origin": "China",
    "review": "(200 reviews)"
  },
  {
    "id": "13",
    "title": "STARWIND SERIES WHITE",
    "pic": "./image/stand3.png",
    "Price": "$46.94",
    "newPrice": "40.00",
    "color": "White",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "origin": "China",
    "review": "(210 reviews)"
  },
  {
    "id": "14",
    "title": "COLOSSUS SERIES GOLDEN",
    "pic": "./image/stand4.png",
    "Price": "$60.00",
    "newPrice": "40.00",
    "color": "Black",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "origin": "China",
    "review": "(200 reviews)"
  },
  {
    "id": "15",
    "title": "STARWIND SERIES BLUE",
    "pic": "./image/stand5.png",
    "Price": "$58.31",
    "newPrice": "40.00",
    "color": "Blue",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "origin": "China",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(210 reviews)"
  },
  {
    "id": "16",
    "title": "COLOSSUS SERIES RED ",
    "pic": "./image/stand6.png",
    "Price": "$60.00",
    "newPrice": "40.00",
    "origin": "China",
    "color": "Red",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(220 reviews)"
  },
  {
    "id": "17",
    "title": "STARWIND SERIES PURPLE",
    "origin": "China",
    "pic": "./image/stand7.png",
    "Price": "$46.94",
    "newPrice": "40.00",
    "color": "Purple",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(230 reviews)"
  },
  {
    "id": "18",
    "title": "FARRATA",
    "pic": "./image/stand8.png",
    "origin": "China",
    "Price": "$66.96",
    "newPrice": "40.00",
    "color": "Black",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(200 reviews)"
  },
  {
    "id": "19",
    "title": "CHEETAH DLX",
    "pic": "./image/stand9.png",
    "origin": "China",
    "Price": "$66.00",
    "newPrice": "50.00",
    "color": "Black",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(210 reviews)"
  },
  {
    "id": "20",
    "title": "MIST AIR DUOS",
    "pic": "./image/stand10.png",
    "origin": "China",
    "Price": "$69.99",
    "newPrice": "50.00",
    "color": "Purple",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(220 reviews)"
  },
  {
    "id": "21",
    "title": "PENTACOOL SERIES BLACK",
    "origin": "China",
    "pic": "./image/stand11.png",
    "Price": "$70.00",
    "newPrice": "50.00",
    "color": "Black",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(230 reviews)"
  },
  {
    "id": "22",
    "title": "PENTACOOL SERIES WHITE",
    "origin": "China",
    "pic": "./image/stand12.png",
    "Price": "$70.00",
    "newPrice": "50.00",
    "color": "Blue",
    "Category": "Standing Fans",
    "Height": "1m - 1.5m",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "40 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Adjust the height to the correct height. Standing electric fans are more compact and lower. Abundant airflow despite its compact size. Adjustable height, to blow air to you whether you are sitting on a sofa or chair. Adjust speed for comfort. Adjust speed with the convenient remote control. Optionally choose from 3 speed levels - low, medium or high. The device can create a pleasant cool breeze at all times. Reliable type W fuse. Electric fans are equipped with “W-type fuses” for all models. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(190 reviews)"
  },
  {
    "id": "23",
    "title": "VIERRA SERIES BLUE",
    "origin": "China",
    "pic": "./image/Tab1.png",
    "Price": "$37.99",
    "newPrice": "30.00",
    "color": "Blue",
    "Category": "Table Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(100 reviews)"
  },
  {
    "id": "24",
    "title": "LINETTO SERIES PURPLE",
    "origin": "China",
    "pic": "./image/Tab2.png",
    "Price": "$36.99",
    "newPrice": "30.00",
    "color": "Purple",
    "Category": "Table Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(110 reviews)"
  },
  {
    "id": "25",
    "title": "LINETTO SERIES BLUE",
    "origin": "China",
    "pic": "./image/Tab3.png",
    "Price": "$36.99",
    "newPrice": "30.00",
    "color": "Blue",
    "Category": "Table Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(100 reviews)"
  },
  {
    "id": "26",
    "title": "VIERA SERIES RED",
    "origin": "China",
    "pic": "./image/Tab4.png",
    "Price": "$37.99",
    "newPrice": "30.00",
    "color": "Red",
    "Category": "Table Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(110 reviews)"
  },
  {
    "id": "27",
    "title": "LINETTO SERIES RED",
    "pic": "./image/Tab5.png",
    "origin": "China",
    "Price": "$37.99",
    "newPrice": "30.00",
    "color": "Red",
    "Category": "Table Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(120 reviews)"
  },
  {
    "id": "28",
    "title": "VIERA SERIES WHITE",
    "origin": "China",
    "pic": "./image/Tab6.png",
    "Price": "$60.00",
    "newPrice": "50.00",
    "color": "White",
    "Category": "Table Fans",
    "Height": "400-700 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "3",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "1 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(130 reviews)"
  },
  {
    "id": "29",
    "title": "TURBO FORCE",
    "pic": "./image/Tab7.jpg",
    "origin": "China",
    "Price": "$29.95",
    "newPrice": "20.00",
    "color": "Black",
    "Category": "Table Fans",
    "Height": "400-600 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "6",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "So compact that it can be placed anywhere. Can be carried from room to room. Compact yet powerful. Adjust speed for comfort. Optionally choose from 3 speed levels - low, medium or high. The speed can be adjusted using the switch on the fan. The device can create a pleasant cool breeze at all times. In case of abnormal operation, the thermal fuse and current fuse will trip to stop the fan. Two times more reliable, providing peace of mind.",
    "review": "(340 reviews)"
  },
  {
    "id": "30",
    "title": "STRIKER SERIES BLACK",
    "origin": "USA",
    "pic": "./image/Exh1.png",
    "Price": "$25.02",
    "newPrice": "20.00",
    "color": "Black",
    "Category": "Exhaust Fans",
    "Height": "400-500 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "5",
    "input": "2.6/20 W",
    "temp": "30 to 120°F",
    "current": "0.037/0.25 A",
    "warranty": "3 year on-site; motor & LED: 5 years",
    "des": "Super low noise: Molded housing and fan surface minimizes noise from the fan and motor escaping to the outside. This technology can also reduce operating noise to an incredibly low level thanks to “Resonant Noise Absorption” operation, creating a quiet environment. Energy saving: The fan is compatible with a DC (Direct Current) motor to reduce power consumption and save energy. DC motors increase in temperature less than AC (Alternating Current) motors, so the recalibration time of DC motors is relatively longer.",
    "review": "(150 reviews)"
  },
  {
    "id": "31",
    "title": "STRIKER SERIES WHITE",
    "origin": "USA",
    "pic": "./image/Exh2.png",
    "Price": "$25.02",
    "newPrice": "20.00",
    "color": "White",
    "Category": "Exhaust Fans",
    "Height": "400-500 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "5",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "3 year on-site; motor & LED: 5 years",
    "des": "Super low noise: Molded housing and fan surface minimizes noise from the fan and motor escaping to the outside. This technology can also reduce operating noise to an incredibly low level thanks to “Resonant Noise Absorption” operation, creating a quiet environment. Energy saving: The fan is compatible with a DC (Direct Current) motor to reduce power consumption and save energy. DC motors increase in temperature less than AC (Alternating Current) motors, so the recalibration time of DC motors is relatively longer.",
    "review": "(110 reviews)"
  },
  {
    "id": "32",
    "title": "CRISP AIR PREMIA",
    "origin": "USA",
    "pic": "./image/Exh3.png",
    "Price": "$33.89",
    "newPrice": "30.00",
    "color": "White",
    "Category": "Exhaust Fans",
    "Height": "400-500 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "No Blaze",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Super low noise: Molded housing and fan surface minimizes noise from the fan and motor escaping to the outside. This technology can also reduce operating noise to an incredibly low level thanks to “Resonant Noise Absorption” operation, creating a quiet environment. Energy saving: The fan is compatible with a DC (Direct Current) motor to reduce power consumption and save energy. DC motors increase in temperature less than AC (Alternating Current) motors, so the recalibration time of DC motors is relatively longer.",
    "review": "(130 reviews)"
  },
  {
    "id": "33",
    "title": "AEROCLEAN V4",
    "pic": "./image/Exh4.png",
    "origin": "USA",
    "Price": "$22.87",
    "newPrice": "20.00",
    "color": "White",
    "Category": "Exhaust Fans",
    "Height": "400-500 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "No Blaze",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "3 year on-site; motor & LED: 5 years",
    "des": "Super low noise: Molded housing and fan surface minimizes noise from the fan and motor escaping to the outside. This technology can also reduce operating noise to an incredibly low level thanks to “Resonant Noise Absorption” operation, creating a quiet environment. Energy saving: The fan is compatible with a DC (Direct Current) motor to reduce power consumption and save energy. DC motors increase in temperature less than AC (Alternating Current) motors, so the recalibration time of DC motors is relatively longer.",
    "review": "(150 reviews)"
  },
  {
    "id": "34",
    "title": "STRIKER SERIES BROWN",
    "origin": "USA",
    "pic": "./image/Exh5.png",
    "Price": "$24.99",
    "newPrice": "20.00",
    "color": "Brown",
    "Category": "Exhaust Fans",
    "Height": "400-500 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "5",
    "input": "2.6/20 W",
    "temp": "42 to 124°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Super low noise: Molded housing and fan surface minimizes noise from the fan and motor escaping to the outside. This technology can also reduce operating noise to an incredibly low level thanks to “Resonant Noise Absorption” operation, creating a quiet environment. Energy saving: The fan is compatible with a DC (Direct Current) motor to reduce power consumption and save energy. DC motors increase in temperature less than AC (Alternating Current) motors, so the recalibration time of DC motors is relatively longer.",
    "review": "(150 reviews)"
  },
  {
    "id": "35",
    "title": "TURBO HEAVY DUTY ",
    "origin": "USA",
    "pic": "./image/Exh6.png",
    "Price": "$50.00",
    "newPrice": "40.00",
    "color": "Black",
    "Category": "Exhaust Fans",
    "Height": "400-500 mm",
    "mode": "LED display",
    "remote": "Include",
    "blaze": "4",
    "input": "2.6/20 W",
    "temp": "32 to 104°F",
    "current": "0.037/0.25 A",
    "warranty": "2 year on-site; motor & LED: 5 years",
    "des": "Super low noise: Molded housing and fan surface minimizes noise from the fan and motor escaping to the outside. This technology can also reduce operating noise to an incredibly low level thanks to “Resonant Noise Absorption” operation, creating a quiet environment. Energy saving: The fan is compatible with a DC (Direct Current) motor to reduce power consumption and save energy. DC motors increase in temperature less than AC (Alternating Current) motors, so the recalibration time of DC motors is relatively longer.",
    "review": "(140 reviews)"
  }
]
export default data;
